###
base_url = "localhost"
title = "Blourvim's blog"
description = "my blog"
default_language = "en"
author = "blourvim"
theme = "halve-z"

compile_sass = true
minify_html = true
generate_feeds = true
build_search_index = true
generate_sitemap = true

taxonomies = [
    { name = "categories", feed = true },
    { name = "tags", feed = true },
]

[search]
include_title = true
include_description = true
include_path = false
include_content = true
index_format = "elasticlunr_json"

[markdown]
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
    { theme = "OneHalfDark", filename = "syntax-theme-dark.css" },
    { theme = "OneHalfLight", filename = "syntax-theme-light.css" },
]
render_emoji = false
external_links_target_blank = true

[slugify]
paths = "safe"
taxonomies = "safe"
anchors = "safe"

[extra]
locale = "en_US"
logo = "icon-192x192.png"
manifest = "manifest.json"
read_time = true
toc = true
csp = true

[extra.placeholders]
tags = false
subtitle = false

[extra.home]
title = "Blourvim"
subtitle = "Mert Yıldız"
glitch = true  
logo = { enabled = true, height = "100", width = "100" }
footer = true

[extra.images]
home = "Wartime_photo_of_Colossus_10.png" 
post_list= "Wartime_photo_of_Colossus_10.png" 
default_post= "Wartime_photo_of_Colossus_10.png"


categories = [
    { name = "media", image = "https://raw.githubusercontent.com/bearcott/8bit-art/master/cities/urban.gif" },
]

[extra.menu]
posts = true
posts_label = "Posts"
links = [
    { name = "Code", url = "@/pages/projects.md" },
]

# [extra.footer]
# enabled = true
# author = true
# copyright = true
# hash = true
# stack = true
# links = [
#     { name = "posts", url = "@/posts/_index.md" },
# ]

[extra.social]
email = "blourvim@gmail.com"
# mastodon = "server/@user_name"
# twitter = "user_name"
# facebook = "user_name"
# codeberg = "username"
github = "blourvim"
# gitlab = "user_name"
# bitbucket = "user_name"
stackoverflow = "27641876/blourvim"
linkedin = "mert-y-2457a020b"
# instagram = "user_name"
# lastfm = "user_name"
# twitch = "user_name"
# reddit = "user_name"
#flickr = "user_name"
# keybase = "user_name"
# hackernews = "user_name"

# [extra.comments]
# system = "none"

# [extra.comments.cactus]
# site = "site_name"
# page_size = 10
# guest_posting = true
# update_interval = 0

# [extra.comments.giscus]
# repo = "user_name/repo"
# repo_id = ""
# category = "Comments"
# category_id = ""
# mapping = "pathname"
# strict = "1"
# reactions = "1"
# lang = "en"

